export const TOURCH_LAST_SAVED = 'TOURCH_LAST_SAVED';
export const SET_CURRENT_NOTE = 'SET_CURRENT_NOTE';
export const SET_CURRENT_NOTE_ID = 'SET_CURRENT_NOTE_ID';
export const PREPEND_TO_NOTES = 'PREPARE_TO_NOTES';
export const DELETE_NOTE = 'DELETE_NOTE';